<wsdl:definitions
     name="dbRefPaises_delete"
     targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/SBExamen/SBProject/dbRefPaises_delete"
     xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/SBExamen/SBProject/dbRefPaises_delete"
     xmlns:jca="http://xmlns.oracle.com/pcbpel/wsdl/jca/"
     xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/"
     xmlns:db="http://xmlns.oracle.com/pcbpel/adapter/db/dbRefPaises_delete"
     xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
    >
  <plt:partnerLinkType name="dbRefPaises_delete_plt" >
    <plt:role name="dbRefPaises_delete_role" >
      <plt:portType name="tns:dbRefPaises_delete_ptt" />
    </plt:role>
  </plt:partnerLinkType>
    <wsdl:types>
      <schema xmlns="http://www.w3.org/2001/XMLSchema" >
        <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/dbRefPaises_delete" schemaLocation="dbRefPaises_delete.xsd" />
      </schema>
    </wsdl:types>
    <wsdl:message name="dbRefPaises_deleteInput_msg">
        <wsdl:part name="dbRefPaises_deleteInput_msg" element="db:dbRefPaises_deleteInput"/>
    </wsdl:message>
    <wsdl:portType name="dbRefPaises_delete_ptt">
        <wsdl:operation name="dbRefPaises_delete">
            <wsdl:input message="tns:dbRefPaises_deleteInput_msg"/>
        </wsdl:operation>
    </wsdl:portType>
</wsdl:definitions>
