<wsdl:definitions targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/SBExamen/SBProject/dbReferencetest" name="dbReferencetest-concrete" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
    <wsdl:import location="dbReferencetest.wsdl" namespace="http://xmlns.oracle.com/pcbpel/adapter/db/SBExamen/SBProject/dbReferencetest"/>
    <wsdl:binding name="dbReferencetest_ptt-binding" type="dbr:dbReferencetest_ptt" xmlns:dbr="http://xmlns.oracle.com/pcbpel/adapter/db/SBExamen/SBProject/dbReferencetest">
        <soap:binding style="document" transport="http://www.bea.com/wli/sb/transports/jca"/>
        <wsdl:operation name="dbReferencetest">
            <soap:operation soapAction="dbReferencetest"/>
            <wsdl:input>
                <soap:body use="literal"/>
            </wsdl:input>
            <wsdl:output>
                <soap:body use="literal"/>
            </wsdl:output>
        </wsdl:operation>
    </wsdl:binding>
</wsdl:definitions>