<wsdl:definitions
     name="dbReferencetest"
     targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/SBExamen/SBProject/dbReferencetest"
     xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/SBExamen/SBProject/dbReferencetest"
     xmlns:jca="http://xmlns.oracle.com/pcbpel/wsdl/jca/"
     xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/"
     xmlns:db="http://xmlns.oracle.com/pcbpel/adapter/db/dbReferencetest"
     xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
    >
  <plt:partnerLinkType name="dbReferencetest_plt" >
    <plt:role name="dbReferencetest_role" >
      <plt:portType name="tns:dbReferencetest_ptt" />
    </plt:role>
  </plt:partnerLinkType>
    <wsdl:types>
      <schema xmlns="http://www.w3.org/2001/XMLSchema" >
        <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/dbReferencetest" schemaLocation="dbReferencetest.xsd" />
      </schema>
    </wsdl:types>
    <wsdl:message name="dbReferencetestInput_msg">
        <wsdl:part name="dbReferencetestInput_msg" element="db:dbReferencetestInput"/>
    </wsdl:message>
    <wsdl:message name="dbReferencetestOutputCollection_msg">
        <wsdl:part name="dbReferencetestOutputCollection" element="db:dbReferencetestOutputCollection"/>
    </wsdl:message>
    <wsdl:portType name="dbReferencetest_ptt">
        <wsdl:operation name="dbReferencetest">
            <wsdl:input message="tns:dbReferencetestInput_msg"/>
            <wsdl:output message="tns:dbReferencetestOutputCollection_msg"/>
        </wsdl:operation>
    </wsdl:portType>
</wsdl:definitions>
