<wsdl:definitions
     name="dbRefPaises_insert"
     targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/SBExamen/SBProject/dbRefPaises_insert"
     xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/SBExamen/SBProject/dbRefPaises_insert"
     xmlns:jca="http://xmlns.oracle.com/pcbpel/wsdl/jca/"
     xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/"
     xmlns:db="http://xmlns.oracle.com/pcbpel/adapter/db/dbRefPaises_insert"
     xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
    >
  <plt:partnerLinkType name="dbRefPaises_insert_plt" >
    <plt:role name="dbRefPaises_insert_role" >
      <plt:portType name="tns:dbRefPaises_insert_ptt" />
    </plt:role>
  </plt:partnerLinkType>
  <plt:partnerLinkType name="dbRefPaises_insert_plt" >
    <plt:role name="dbRefPaises_insert_role" >
      <plt:portType name="tns:dbRefPaises_insert_ptt" />
    </plt:role>
  </plt:partnerLinkType>
    <wsdl:types>
      <schema xmlns="http://www.w3.org/2001/XMLSchema" >
        <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/dbRefPaises_insert" schemaLocation="dbRefPaises_insert.xsd" />
      </schema>
      <schema xmlns="http://www.w3.org/2001/XMLSchema" >
        <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/dbRefPaises_insert" schemaLocation="dbRefPaises_insert.xsd" />
      </schema>
    </wsdl:types>
    <wsdl:message name="dbRefPaises_insertInput_msg">
        <wsdl:part name="dbRefPaises_insertInput_msg" element="db:dbRefPaises_insertInput"/>
    </wsdl:message>
    <wsdl:portType name="dbRefPaises_insert_ptt">
        <wsdl:operation name="dbRefPaises_insert">
            <wsdl:input message="tns:dbRefPaises_insertInput_msg"/>
        </wsdl:operation>
    </wsdl:portType>
</wsdl:definitions>
