<wsdl:definitions targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/SBExamen/SBProject/dbRefPaises_insert" name="dbRefPaises_insert-concrete" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
    <wsdl:import location="dbRefPaises_insert.wsdl" namespace="http://xmlns.oracle.com/pcbpel/adapter/db/SBExamen/SBProject/dbRefPaises_insert"/>
    <wsdl:binding name="dbRefPaises_insert_ptt-binding" type="dbr:dbRefPaises_insert_ptt" xmlns:dbr="http://xmlns.oracle.com/pcbpel/adapter/db/SBExamen/SBProject/dbRefPaises_insert">
        <soap:binding style="document" transport="http://www.bea.com/wli/sb/transports/jca"/>
        <wsdl:operation name="dbRefPaises_insert">
            <soap:operation soapAction="dbRefPaises_insert"/>
            <wsdl:input>
                <soap:body use="literal"/>
            </wsdl:input>
        </wsdl:operation>
    </wsdl:binding>
</wsdl:definitions>